language: python
python: 3.6
dist: bionic
sudo: true
install:
 - git config credential.helper "store --file=.git/credentials"
 - echo $cred > .git/credentials
script:
 - git config --global user.email "monkeyboy2805@gmail.com"
 - git config --global user.name "monkeyboy2805"
 - curl --url https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tgz --location --output ./source.tgz
 - tar -xzf ./source.tgz
 - python ./ci/CI.py
 - git reset --hard
 - git checkout $TRAVIS_BRANCH
 - python ./ci/build/update/CIRepoAutoUpdate.py
