language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.6.0"
- "3.6.1"
- "3.6.2"
- "3.6.3"
- "3.6.4"
- "nightly"
env:
- DJANGO_VERSION==1.11.8
- DJANGO_VERSION==2.0.1
install:
- pip install -q Django=$DJANGO_VERSION 
- git config --global user.name "Monkeyboy2805"
- git config --global user.email "monkeyboy2805@gmail.com"
- git config --global user.password $password
script:
- python ./ci/CI.py
