language: python
python:
- "3.6-dev"
- "3.6"
- "nightly"
env:
- DJANGO_VERSION==1.10.5
install:
- pip install -q Django=$DJANGO_VERSION 
script:
- python CI.py
notifications:
  gitter:
    on_success: always
