language: python
python:
 - "3.2" 
 - "3.3" 
 - "3.4" 
 - "3.5" 
 - "3.5-dev" 
 - "nightly"
script: nosetests
env: 
 - DJANGO_VERSION==1.10.3 
 - DJANGO_VERSION==1.10.2
 - DJANGO_VERSION==1.10.1 
 - DJANGO_VERSION==1.10
 - DJANGO_VERSION==1.9.10
 - DJANGO_VERSION==1.8.15

install:
 - pip install -q Django=$DJANGO_VERSION 
 - python /Lolex-Tools/System/Frame/Main/JTTools.py 
 - python /Lolex-Tools/System/Frame/Install/JTToolsInstaller.py
