language: python
python:
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - git config credential.helper "store --file=.git/credentials"
 - echo $cred > .git/credentials
script:
 - git config --global user.email "monkeyboy2805@gmail.com"
 - git config --global user.name "monkeyboy2805"
 - python ./ci/CI.py
 - git reset --hard
 - git checkout $TRAVIS_BRANCH
 - python ./ci/build/update/CIRepoAutoUpdate.py
