language: python
python:
 - "3.6.4"
env:
 - DJANGO_VERSION==2.0.1
install:
 - pip install -q Django=$DJANGO_VERSION
script:
 - python ./ci/CI.py
 - git config --global user.email "monkeyboy2805@gmail.com"
 - git config --global user.name "monkeyboy2805"
 - git add *
 - git commit -m "Update here :P"
 - git push
