language: python
python:
 - "3.6.5"
install:
 - git config credential.helper "store --file=.git/credentials"
 - echo $cred > .git/credentials
script:
 - git config --global user.email "monkeyboy2805@gmail.com"
 - git config --global user.name "monkeyboy2805"
 - git checkout latest
 - python ./ci/build/cron/cron.py
