language: python
python:
 - "3.2" 
 - "3.3" 
 - "3.4" 
 - "3.5" 
 - "3.5-dev" 
 - "nightly"
script: nosetests
env: 
 - DJANGO_VERSION==1.10.3 
 - DJANGO_VERSION==1.10.2
 - DJANGO_VERSION==1.10.1 
 - DJANGO_VERSION==1.10
 - DJANGO_VERSION==1.9.10
 - DJANGO_VERSION==1.9.9
 - DJANGO_VERSION==1.9.8
 - DJANGO_VERSION==1.9.7
 - DJANGO_VERSION==1.9.6 
 - DJANGO_VERSION==1.9.5
 - DJANGO_VERSION==1.9.4 
 - DJANGO_VERSION==1.9.3
 - DJANGO_VERSION==1.9.2
 - DJANGO_VERSION==1.9.1
 - DJANGO_VERSION==1.9.0
 - DJANGO_VERSION==1.8.15
 - DJANGO_VERSION==1.8.14
 - DJANGO_VERSION==1.8.13
 - DJANGO_VERSION==1.8.12
 - DJANGO_VERSION==1.8.11
 - DJANGO_VERSION==1.8.10
 - DJANGO_VERSION==1.8.9
 - DJANGO_VERSION==1.8.8
 - DJANGO_VERSION==1.8.7
 - DJANGO_VERSION==1.8.6
 - DJANGO_VERSION==1.8.5
 - DJANGO_VERSION==1.8.4
 - DJANGO_VERSION==1.8.3
 - DJANGO_VERSION==1.8.2
 - DJANGO_VERSION==1.8.1
 - DJANGO_VERSION==1.8
install:
 - pip install -q Django=$DJANGO_VERSION 
 - python /Lolex-Tools/System/Frame/Main/JTTools.py 
 - python /Lolex-Tools/System/Frame/Install/JTToolsInstaller.py