language: python
python:
 - "3.6.4"
env:
 - DJANGO_VERSION==2.0.1
install:
 - pip install -q Django=$DJANGO_VERSION
 - git config credential.helper "store --file=.git/credentials"
 - echo $cred > .git/credentials
script:
 - git config --global user.email "monkeyboy2805@gmail.com"
 - git config --global user.name "monkeyboy2805"
 - git checkout $TRAVIS_BRANCH
 - python ./ci/CI.py
